return {
  "nvim-treesitter/nvim-treesitter-textobjects",
  dependencies = { "nvim-treesitter/nvim-treesitter" },
  config = function()
    local move   = require("nvim-treesitter-textobjects.move")
    local select = require("nvim-treesitter-textobjects.select")
    local swap   = require("nvim-treesitter-textobjects.swap")

    -- ── Move ────────────────────────────────────────────
    vim.keymap.set("n", "]f", function()
      move.goto_next_start("@function.outer")
    end,     { desc = "Next function start" })
    vim.keymap.set("n", "]F", function()
      move.goto_next_end("@function.outer")
    end,       { desc = "Next function end" })
    vim.keymap.set("n", "[f", function()
      move.goto_previous_start("@function.outer")
    end, { desc = "Prev function start" })
    vim.keymap.set("n", "[F", function()
      move.goto_previous_end("@function.outer")
    end,   { desc = "Prev function end" })
    vim.keymap.set("n", "]c", function()
      move.goto_next_start("@class.outer")
    end,        { desc = "Next class start" })
    vim.keymap.set("n", "]C", function()
      move.goto_next_end("@class.outer")
    end,          { desc = "Next class end" })
    vim.keymap.set("n", "[c", function()
      move.goto_previous_start("@class.outer")
    end,    { desc = "Prev class start" })
    vim.keymap.set("n", "[C", function()
      move.goto_previous_end("@class.outer")
    end,      { desc = "Prev class end" })

    -- ── Select ──────────────────────────────────────────
    vim.keymap.set({ "x", "o" }, "af", function()
      select.select_textobject("@function.outer", "textobjects")
    end, { desc = "Around function" })
    vim.keymap.set({ "x", "o" }, "if", function()
      select.select_textobject("@function.inner", "textobjects")
    end, { desc = "Inside function" })
    vim.keymap.set({ "x", "o" }, "ac", function()
      select.select_textobject("@class.outer", "textobjects")
    end,    { desc = "Around class" })
    vim.keymap.set({ "x", "o" }, "ic", function()
      select.select_textobject("@class.inner", "textobjects")
    end,    { desc = "Inside class" })
    vim.keymap.set({ "x", "o" }, "aa", function()
      select.select_textobject("@parameter.outer", "textobjects")
    end, { desc = "Around parameter" })
    vim.keymap.set({ "x", "o" }, "ia", function()
      select.select_textobject("@parameter.inner", "textobjects")
    end, { desc = "Inside parameter" })
    vim.keymap.set({ "x", "o" }, "ai", function()
      select.select_textobject("@conditional.outer", "textobjects")
    end, { desc = "Around conditional" })
    vim.keymap.set({ "x", "o" }, "ii", function()
      select.select_textobject("@conditional.inner", "textobjects")
    end, { desc = "Inside conditional" })
    vim.keymap.set({ "x", "o" }, "al", function()
      select.select_textobject("@loop.outer", "textobjects")
    end,     { desc = "Around loop" })
    vim.keymap.set({ "x", "o" }, "il", function()
      select.select_textobject("@loop.inner", "textobjects")
    end,     { desc = "Inside loop" })

    -- ── Swap ────────────────────────────────────────────
    vim.keymap.set("n", "<leader>na", function()
      swap.swap_next("@parameter.inner")
    end,     { desc = "Swap param with next" })
    vim.keymap.set("n", "<leader>pa", function()
      swap.swap_previous("@parameter.inner")
    end, { desc = "Swap param with prev" })
  end,
}
